apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rearc-app
  name: rearc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rearc-app
  template:
    metadata:
      labels:
        app: rearc-app
    spec:
      containers:
      - name: my-rearc-app
        image: kuga01/rearc:554a774
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/rearc-log/
          name: storage-volume
      volumes:
      - name: storage-volume
        hostPath:
          path: /var/lib/rearc
          type: DirectoryOrCreate
