---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rearc-app
    k8s-app: rearc-app
  name: rearc-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: ClusterIP # LoadBalancer # NodePort # 
  selector:
    app: rearc-app
